name: exogithubactions
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build du projet exercice
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: voir le contenu du repo
        run: ls -R  
      - name: Installer les dépendences
        run: npm i
      - name: Tester le projet
        run: npm test
      - name: Build le projet 
        run: npm run build
      - name: Uploader le résultat du build comme artefact
        uses: actions/upload-artifact@v4
        with:
          name: mon-exo
          path: dist/
      - name: Afficher l'artefact
        run: ls dist/

  retrieve-artifact:
    name: Récupérer l'artefact et afficher la liste des fichiers
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Récupérer l'artefact
        uses: actions/download-artifact@v4
        with:
          name: mon-exo
          path: artifacts
      - name: Afficher la liste des fichiers de l'artefact
        run: ls -R artifacts
