name: Démo outputs
run-name: "Exécution du workflow ${{github.workflow}} pour le commit ${{github.event.head_commit.message}}"
on: push
jobs:
  job1:
    name: Génère param de sortie
    runs-on: ubuntu-latest
    outputs:
      sortie1: ${{steps.etape1.outputs.VAR1}}
      sortie2: ${{steps.etape2.outputs.VAR2}}
    steps:
    - id: etape1
      name: Set VAR1
      run: echo "VAR1=Hello" >> $GITHUB_OUTPUT
    - id: etape2
      name: Set VAR2
      run: echo "VAR2=World" >> $GITHUB_OUTPUT
    - id: etape3
      name: echo VAR1 VAR2
      run: echo ${{steps.etape1.outputs.VAR1}} ${{steps.etape2.outputs.VAR2}}

  job2:
    name: Recup param job1
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: echo sortie1 sortie2
        run: echo ${{needs.job1.outputs.sortie1}} ${{needs.job2.outputs.sortie2}}